apiVersion: test.raehowe.com/v1alpha1
kind: HelloWorld
metadata:
  labels:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: helloworld-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: helloworld-sample
spec:
  # TODO(user): Add fields here
